before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: macOS
    windows: Windows
    amd64: x86_64
  wrap_in_directory: true
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
